export {default as AgeView} from './AgeView';
export {default as DislikedFoodView} from './DislikedFoodView';
export {default as FavoriteFoodView} from './FavoriteFoodView';
export {default as FoodAllergiesView} from './FoodAllergiesView';
export {default as FoodPracticeView} from './FoodPracticeView';
export {default as GenderView} from './GenderView';
export {default as GoalView} from './GoalView';
export {default as HeightView} from './HeightView';
export {default as WorkoutView} from './WorkoutView';
